name = "PkgHelpers"
uuid = "a562b63c-6e73-49f2-82ca-bd0905bcffd6"
authors = ["Uwe Fechner <uwe.fechner.msc@gmail.com> and contributors"]
version = "0.3.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
Pkg = "1.4 - 1.12"
julia = "1.4 - 1.12"
TOML = "~1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Documenter", "Test"]

